/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as randomGeneratorSol from "./RandomGenerator.sol";
export type { randomGeneratorSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Duel } from "./Duel";
export type { Governance } from "./Governance";
