/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DuelInterface } from "./DuelInterface";
export type { GovernanceInterface } from "./GovernanceInterface";
export type { RandomnessInterface } from "./RandomnessInterface";
