/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as randomGeneratorSol from "./RandomGenerator.sol";
export * as interfaces from "./interfaces";
export { Duel__factory } from "./Duel__factory";
export { Governance__factory } from "./Governance__factory";
