/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  DuelInterface,
  DuelInterfaceInterface,
} from "../../../contracts/interfaces/DuelInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "endDuel",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class DuelInterface__factory {
  static readonly abi = _abi;
  static createInterface(): DuelInterfaceInterface {
    return new utils.Interface(_abi) as DuelInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DuelInterface {
    return new Contract(address, _abi, signerOrProvider) as DuelInterface;
  }
}
