/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  GovernanceInterface,
  GovernanceInterfaceInterface,
} from "../../../contracts/interfaces/GovernanceInterface";

const _abi = [
  {
    inputs: [],
    name: "duel",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "randomness",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class GovernanceInterface__factory {
  static readonly abi = _abi;
  static createInterface(): GovernanceInterfaceInterface {
    return new utils.Interface(_abi) as GovernanceInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GovernanceInterface {
    return new Contract(address, _abi, signerOrProvider) as GovernanceInterface;
  }
}
