/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DuelInterface__factory } from "./DuelInterface__factory";
export { GovernanceInterface__factory } from "./GovernanceInterface__factory";
export { RandomnessInterface__factory } from "./RandomnessInterface__factory";
