/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  RandomnessInterface,
  RandomnessInterfaceInterface,
} from "../../../contracts/interfaces/RandomnessInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_roomId",
        type: "bytes32",
      },
    ],
    name: "getRandom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "randomNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class RandomnessInterface__factory {
  static readonly abi = _abi;
  static createInterface(): RandomnessInterfaceInterface {
    return new utils.Interface(_abi) as RandomnessInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RandomnessInterface {
    return new Contract(address, _abi, signerOrProvider) as RandomnessInterface;
  }
}
