/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "LinkTokenInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LinkTokenInterface__factory>;
    getContractFactory(
      name: "VRFCoordinatorV2Interface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VRFCoordinatorV2Interface__factory>;
    getContractFactory(
      name: "VRFConsumerBaseV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VRFConsumerBaseV2__factory>;
    getContractFactory(
      name: "Duel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Duel__factory>;
    getContractFactory(
      name: "Governance",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Governance__factory>;
    getContractFactory(
      name: "DuelInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DuelInterface__factory>;
    getContractFactory(
      name: "GovernanceInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GovernanceInterface__factory>;
    getContractFactory(
      name: "RandomnessInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RandomnessInterface__factory>;
    getContractFactory(
      name: "RandomNumberGenerator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RandomNumberGenerator__factory>;

    getContractAt(
      name: "LinkTokenInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LinkTokenInterface>;
    getContractAt(
      name: "VRFCoordinatorV2Interface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.VRFCoordinatorV2Interface>;
    getContractAt(
      name: "VRFConsumerBaseV2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.VRFConsumerBaseV2>;
    getContractAt(
      name: "Duel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Duel>;
    getContractAt(
      name: "Governance",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Governance>;
    getContractAt(
      name: "DuelInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DuelInterface>;
    getContractAt(
      name: "GovernanceInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GovernanceInterface>;
    getContractAt(
      name: "RandomnessInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.RandomnessInterface>;
    getContractAt(
      name: "RandomNumberGenerator",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.RandomNumberGenerator>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
